### PR TITLE
Add Bluestore commit latency raw dataset to validate latModel (#12)

### LINKED ISSUE #5: Update latModel to better fit BlueStore behavior
The latencies in BlueStore are not only dependent on the request size but also on latency spikes due to compaction. So there should at least be an additional heavy-tailed latency component (based on a suggestion by @athanatos).

### LINKED ISSUE #12: Create Jupyter notebook to analyze and validate latModel

### PR DESCRIPTION
**Pull request by carlosmalt**
The raw data set needs to contain *all* measurements (no clean-up please -- that's what "raw" means).

### CODE REVIEW

**Comment by carlosmalt** [comment]
Where is the code that shows how `dump-codel-tests.csv` was derived? I also don't understand how all files can be raw _except_ `dump-codel-tests.csv` but at the same time `dump-codel-tests.csv` was generated in BlueStore.

**Comment by carlosmalt** [comment]
Also, the number of latency measurements for each size seem to be all over the place (assuming I'm interpreting the csv files correctly): 
```
gallus:base-batch-1[0] wc -l dump_kv_sync_lat_vec-*.csv
   17532 dump_kv_sync_lat_vec-1048576.csv
   51761 dump_kv_sync_lat_vec-131072.csv
   77602 dump_kv_sync_lat_vec-16384.csv
   11155 dump_kv_sync_lat_vec-2097152.csv
   39485 dump_kv_sync_lat_vec-262144.csv
   73771 dump_kv_sync_lat_vec-32768.csv
   86196 dump_kv_sync_lat_vec-4096.csv
    6351 dump_kv_sync_lat_vec-4194304.csv
   28261 dump_kv_sync_lat_vec-524288.csv
   64008 dump_kv_sync_lat_vec-65536.csv
   81787 dump_kv_sync_lat_vec-8192.csv
    6315 dump_kv_sync_lat_vec-8388608.csv
  544224 total
gallus:base-batch-1[0] 
```
When you derived `dump-codel-tests.csv`, did you make sure that you used the same number of measurements from each file? For example, you could exclude 4MB and 8MB and use the first _x + 10,000_ measurements from each file, where _x_ is the number of measurements you skip at the beginning to reach steady state.

**Comment by carlosmalt** [comment]
I've added timelines of `dump_kv_sync_lat_vec-*.csv` to `experiments/latModel/latModel.ipynb`. You can see that you probably want to remove the first 1000 measurements.

**Comment by carlosmalt** [comment]
@yzhan298 Can you please try to undo the merge? I was going to maintain this branch to discuss the validation of the latModel. This is obviously not complete yet.

**Comment by yzhan298** [comment]
> @yzhan298 Can you please try to undo the merge? I was going to maintain this branch to discuss the validation of the latModel. This is obviously not complete yet.

sure, let me undo the merge.

**Comment by carlosmalt** [comment]
Looks like we still have the pull request but it's not clear that it still can be used...

**Comment by yzhan298** [comment]
> Where is the code that shows how `dump-codel-tests.csv` was derived? I also don't understand how all files can be raw _except_ `dump-codel-tests.csv` but at the same time `dump-codel-tests.csv` was generated in BlueStore.

The `dump-codel-tests.csv` is generated from the Ceph source code. Originally, I added the processing function in admin socket like this:
```
throttle.kv_sync_lat_vec = vector<double>(throttle.kv_sync_lat_vec.begin()+10, throttle.kv_sync_lat_vec.end()-10); // remove the first and last 10 elements
double kv_sync_p99_lat = throttle.kv_sync_lat_vec[(int)(throttle.kv_sync_lat_vec.size()*0.99 - 1)]; // calculate the 99% latency
```
That's why only the `dump-codel-tests.csv` contains data with out first and last data points.

I found a way to iterate the generated raw files (with `glob`) and generate the desired result in codel-testing script. Will update the plot script in the repo shortly.

**Comment by yzhan298** [comment]
> Also, the number of latency measurements for each size seem to be all over the place (assuming I'm interpreting the csv files correctly):
> 
> ```
> gallus:base-batch-1[0] wc -l dump_kv_sync_lat_vec-*.csv
>    17532 dump_kv_sync_lat_vec-1048576.csv
>    51761 dump_kv_sync_lat_vec-131072.csv
>    77602 dump_kv_sync_lat_vec-16384.csv
>    11155 dump_kv_sync_lat_vec-2097152.csv
>    39485 dump_kv_sync_lat_vec-262144.csv
>    73771 dump_kv_sync_lat_vec-32768.csv
>    86196 dump_kv_sync_lat_vec-4096.csv
>     6351 dump_kv_sync_lat_vec-4194304.csv
>    28261 dump_kv_sync_lat_vec-524288.csv
>    64008 dump_kv_sync_lat_vec-65536.csv
>    81787 dump_kv_sync_lat_vec-8192.csv
>     6315 dump_kv_sync_lat_vec-8388608.csv
>   544224 total
> gallus:base-batch-1[0] 
> ```
> 
> When you derived `dump-codel-tests.csv`, did you make sure that you used the same number of measurements from each file? For example, you could exclude 4MB and 8MB and use the first _x + 10,000_ measurements from each file, where _x_ is the number of measurements you skip at the beginning to reach steady state.

When switched to the `io total size` in fio, the error 
```
fio: pid=30616, err=22/file:io_u.c:1787, func=io_u error, error=Invalid argument
```
 still exists, so I smithed back to time-based measurement.

**Comment by yzhan298** [comment]
>For example, you could exclude 4MB and 8MB and use the first _x + 10,000_ measurements from each file, where _x_ is the number of measurements you skip at the beginning to reach steady state.

This is a good idea. I can still use the time based method to generate the data, but show first `x + 10000` data points in the csv files to generate graphs.

**Pull request merged**
